# Generated by Django 3.2.25 on 2025-05-02 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='recipie_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('desc', models.CharField(max_length=250)),
                ('ingre', models.CharField(max_length=150)),
                ('img', models.FileField(upload_to='pics')),
                ('instr', models.CharField(max_length=250)),
            ],
        ),
    ]
