# Generated by Django 3.2.25 on 2025-05-02 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipie_tbl',
            name='img',
            field=models.FileField(upload_to='pic'),
        ),
    ]
