# Generated by Django 3.2.25 on 2025-05-02 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_recipie_tbl_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipie_tbl',
            name='img',
            field=models.FileField(upload_to='images'),
        ),
    ]
