# Generated by Django 3.2.25 on 2025-05-02 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_recipie_tbl_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipie_tbl',
            name='ingre',
            field=models.CharField(max_length=150),
        ),
    ]
